AllCops:
  TargetRubyVersion: "2.1"
  Exclude:
    - "spec/**/*"
Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

HashSyntax:
  Enabled: false

MethodName:
  Enabled: false

StringLiterals:
  Enabled: false
